import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import NextAuthSessionProvider from "./provider";
// import { AuthProvider } from "@descope/nextjs-sdk";
const inter = Outfit({ subsets: ["latin"] });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
// className={`${geistSans.variable} ${geistMono.variable} antialiased`}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <AuthProvider projectId="P31zfxMnXjWYZ8I2otSq6feNGk8g">
    <html lang="en">
      <body className={inter.className}>
        <NextAuthSessionProvider>
          <div className="mx-6 md:mx-16">
            <Header />
            {children}
          </div>
        </NextAuthSessionProvider>
      </body>
    </html>
    // </AuthProvider>
  );
}

